version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: portfolio_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: securedpwd!
      MYSQL_DATABASE: portfolio
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appPwd2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
